3NF DATA MODEL: {

    DST_3NF_AIRCRAFTS: {
        shape: sql_table
        style: {fill: red}
        AIRCRAFTCODE: VARCHAR {constraint: [primary_key]}
        AIRLINEEQUIPCODE: VARCHAR
        NAME: VARCHAR
    }

    DST_3NF_AIRLINES: {
        shape: sql_table
        style: {fill: red}
        AIRLINEID: VARCHAR {constraint: [primary_key]}
        NAME: VARCHAR
		AIRLINE_ICAO: VARCHAR
    }
	
    DST_3NF_AIRPORTS: {
        shape: sql_table
        style: {fill: red}
        AIRPORTCODE: VARCHAR {constraint: [primary_key]}
        CITYCODE: VARCHAR
        COUNTRYCODE: VARCHAR
		NAME: VARCHAR
		LATITUDE: VARCHAR
		LONGITUDE: VARCHAR
		LOCATIONTYPE: VARCHAR
    }
	
    DST_3NF_CITIES: {
        shape: sql_table
        style: {fill: red}
		ID_CITYCODE: NUMBER {constraint: [primary_key]}
		CITYCODE: VARCHAR
        NAME: VARCHAR
        AIRPORTCODE: VARCHAR
		COUNTRYCODE: VARCHAR
    }
	
    DST_3NF_COUNTRIES: {
        shape: sql_table
        style: {fill: red}
        COUNTRYCODE: VARCHAR {constraint: [primary_key]}
        COUNTRYNAME: VARCHAR
    }	
	
    DST_3NF_FLIGHT_SCHEDULES: {
        shape: sql_table
        style: {fill: red}
        ID_FLIGHT_SCHEDULES: NUMBER {constraint: [primary_key]}
		FLIGHTNUMBER: NUMBER
		AIRLINEID: VARCHAR
        SERVICETYPE: VARCHAR
        AIRCRAFTTYPE: VARCHAR
		AIRCRAFTARRIVALTIMELT: NUMBER
		AIRCRAFTOWNER: VARCHAR
		DESTINATION: VARCHAR
		ORIGIN: VARCHAR
		DAYSOFOPERATION: NUMBER
		ENDATE: VARCHAR
		STARTDATE: VARCHAR
    }	
	
	DST_3NF_LOCATIONTYPE: {
		shape: sql_table
		style: {fill: red}
		ID_LOCATIONTYPE: NUMBER {constraint: [primary_key]}
		LOCATIONTYPE: VARCHAR
	}
	
	DST_3NF_SERVICETYPE: {
		shape: sql_table
		style: {fill: red}
		ID_SERVICETYPE: NUMBER {constraint: [primary_key]}
		SERVICETYPE: VARCHAR
	}	
	
    
    #generic fact_table
    #countries.id_country -> generic_fact_table.id_country: 1,n  
	DST_3NF_LOCATIONTYPE.ID_LOCATIONTYPE -> DST_3NF_AIRPORTS.ID_LOCATIONTYPE: 1, N
	DST_3NF_SERVICETYPE.ID_SERVICETYPE -> DST_3NF_FLIGHT_SCHEDULES.SERVICETYPE:1, N
	DST_3NF_COUNTRIES.CITYCODE -> DST_3NF_AIRPORTS.COUNTRYCODE: 1, N
	DST_3NF_CITIES.CITYCODE -> DST_3NF_AIRPORTS.CITYCODE: 1, N
	DST_3NF_AIRLINES.AIRLINEID -> DST_3NF_FLIGHT_SCHEDULES.AIRLINEID; 1, N
	DST_3NF_AIRCRAFTS.AIRCRAFTCODE -> DST_3NF_FLIGHT_SCHEDULES.AIRCRAFTCODE: 1, N
	DST_3NF_AIRPORTS.AIRCRAFTCODE -> DST_3NF_FLIGHT_SCHEDULES.ORIGIN: 1, N
	DST_3NF_AIRPORTS.AIRCRAFTCODE -> DST_3NF_FLIGHT_SCHEDULES.DESTINATION: 1, N
	
    
}