DST Airlines: {
  countries: {
    shape: sql_table
    style: {fill: blue}
    id_country: integer {constraint: primary_key}
    country_code: varchar
    country_name: varchar
  }

  timezones: {
    shape: sql_table
    style: {fill: blue}
    id_timezone: integer {constraint: primary_key}
    utc_offset: float
    name: varchar
  }

  cities: {
    shape: sql_table
    style: {fill: blue}
    id_city: integer {constraint: primary_key}
    city_code: varchar
    city_name: varchar
    id_timezone: integer {constraint: foreign_key}
    id_country: integer {constraint: foreign_key}
  }

  airports: {
    shape: sql_table
    style: {fill: blue}
    id_airport: integer {constraint: primary_key}
    airport_code: varchar
    coordinates: geometry
    id_city: integer {constraint: foreign_key}
  }

  aircrafts: {
    shape: sql_table
    style: {fill: blue}
    id_aircraft: integer {constraint: primary_key}
    aircraft_code: varchar
    name: varchar
    id_equipement: integer {constraint: foreign_key}
  }

  airlines: {
    shape: sql_table
    style: {fill: blue}
    id_airline: integer {constraint: primary_key}
    airlineID: varchar
    AirlineID_ICAO: varchar
    name: varchar
  }

  flight_schedules: {
    shape: sql_table
    style: {fill: purple}
    id_flight_schedules: integer {constraint: primary_key}
    duration: varchar
    departure_airportCode: varchar
    departure_scheduledTimeLocal_Datetime: datetime
    arrival_airportCode: varchar
    arrival_scheduledTimeLocal_Datetime: datetime
    marketingCarrier_airlineID: varchar
    flightNumber: integer
    operatingCarrier_airlineID: varchar
    equipment_aircraftCode: integer
    details_stops_stopQuantity: integer
    details_daysOfOperation: integer
  }

# 
  lounges: {
    shape: sql_table
    style: {fill: violet}
    id_lounge: integer  {constraint: primary_key}
    location: varchar
    opening_hours: varchar
    id_feature: {constraint: foreign_key}
    MagazinesAndNews: varchar # to check
    airport_id: integer {constraint: foreign_key}
  }

  features:{
    shape: sql_table
    style: {fill: violet}
    id_feature: integer  {constraint: primary_key}
    feature_name: varchar
  }

  equipments: {
    shape: sql_table
    style: {fill: violet}
    id_equipement: integer  {constraint: primary_key}
    equipement_name: varchar
  }

  # flight_statuses: {
    # shape: sql_table
    # style: {fill: blue}
    # id_fligth_status: integer  {constraint: primary_key}
    # name
  # }

  fact_table_flights_schedules_airport: {
    shape: sql_table
    style: {fill: black}
    id_fact_table_flights_schedules_airport: integer {constraint: primary_key}
    id_airport: integer {constraint: foreign_key}
    id_flight_schedules: integer {constraint: foreign_key}
    number_of_flights: integer
    flight_duration: float
    number_of_stops: integer
    id_time: integer {constraint: foreign_key}

}

fact_table_flights_schedules_airlines: {
  shape: sql_table
  style: {fill: black}
  id_fact_table_flights_schedules_airlines: integer {constraint: primary_key}
  id_airline: integer {constraint: foreign_key}
  id_flight_schedules: integer {constraint: foreign_key}
  number_of_flights: integer
  flight_duration: float
  number_of_stops: integer
  id_time: integer {constraint: foreign_key}

}


fact_table_flights_schedules_aircraft: {
  shape: sql_table
  style: {fill: black}
  id_fact_table_flights_schedules_aircraft: integer {constraint: primary_key}
  id_aircraft: integer {constraint: foreign_key}
  id_flight_schedules: integer {constraint: foreign_key}
  number_of_flights: integer
  flight_duration: float
  number_of_stops: integer
  id_time: integer {constraint: foreign_key}

}

time: {
  shape: sql_table
  style: {fill: orange}
  id_time: integer {constraint: primary_key}
  date: datetime
  year: integer
  month: integer
  day: integer
  hour: integer
}


#snowflake relationships
timezones -> cities <- countries
cities -> airports <- lounges <- features
#airports -> flight_schedules
#time -> flight_schedules
#aircrafts -> flight_schedules
#airlines -> flight_schedule
equipments -> aircrafts

#fact_table_flight_schedules_countries
flight_schedules.id_flight_schedules -> fact_table_flights_schedules_airport.id_flight_schedules: 1,n
airports.id_airport -> fact_table_flights_schedules_airport.id_airport: 1,n
time.id_time -> fact_table_flights_schedules_airport.id_time: 1,n

#fact_table_flights_schedules_airlines
flight_schedules.id_flight_schedules -> fact_table_flights_schedules_airlines.id_airline: 1,n
airlines.airlineID -> fact_table_flights_schedules_airlines.id_airline: 1,n
time.id_time -> fact_table_flights_schedules_airlines.id_time: 1,n

#fact_table_flights_schedules_aircraft
flight_schedules.id_flight_schedules -> fact_table_flights_schedules_aircraft.id_flight_schedules: 1,n
aircrafts.id_aircraft -> fact_table_flights_schedules_aircraft.id_aircraft: 1,n
time.id_time -> fact_table_flights_schedules_aircraft.id_time: 1,n

}


### TODO
# voir pour flight / flight_status (mais lien vaec time et airports: https://developer.lufthansa.com/docs/api_details/operations/Flight_Status_Response
# MagazinesAndNews in lounges ?

