DST Airlines: {

    countries: {
        shape: sql_table
        style: {fill: blue}
        id_country: integer {constraint: primary_key}
        country_code: varchar 
        country_name: varchar
    }

    cities: {
        shape: sql_table
        style: {fill: blue}
        id_city: integer {constraint: primary_key}
        city_code: varchar
        city_name: varchar
        id_timezone: integer {constraint: foreign_key}
        id_country: integer {constraint: foreign_key}
        id_airport: integer {constraint: foreign_key}
    }

    timezones: {
        shape: sql_table
        style: {fill: blue}
        id_timezone: integer {constraint: primary_key}
        utc_offset: float
    }

    airports: {
        shape: sql_table
        style: {fill: blue}
        id_airport: integer {constraint: primary_key}
        airport_code: varchar 
        id_city: integer {constraint: foreign_key}
        coordinates: geometry
    }

    aircrafts: {
        shape: sql_table
        style: {fill: blue}
        id_aircraft: integer {constraint: primary_key}
        aircraft_code: varchar
        name: varchar
        equip_code: varchar
    }

    airlines: {
        shape: sql_table
        style: {fill: blue}
        id_airline: integer {constraint: primary_key}
        airlineID: varchar 
        AirlineID_ICAO: varchar
        name: varchar
    }

    flight_schedules: {
        shape: sql_table
        style: {fill: green}
        id_flight_schedules: integer {constraint: primary_key}
        duration: varchar
        departure_airportCode: varchar
        departure_scheduledTimeLocal_Datetime: datetime
        arrival_airportCode: varchar
        arrival_scheduledTimeLocal_Datetime: datetime
        marketingCarrier_airlineID: varchar
        flightNumber: integer
        operatingCarrier_airlineID: varchar
        equipment_aircraftCode: integer
        details_stops_stopQuantity: integer
        details_daysOfOperation: integer
    }

    generic_fact_table: {
        shape: sql_table
        style: {fill: black}
        id_fact_table: integer {constraint: primary_key} 
        id_country: integer
        id_city: integer
        id_language: integer
        id_airport: integer
        id_aircraft: integer
        id_airline: integer
        id_flight_schedules: integer
        id_timezone: integer
        measure_1: float
        measure_2: float
        measure_3: float
        Measure_4: float
    }

    fact_table_flights_countries: {
        shape: sql_table
        style: {fill: black}
        id_fact_table_flights_countries: integer {constraint: primary_key}
        id_country: integer
        id_flight_schedules: integer
        number_of_flights: integer
        flight_duration: float
        number_of_stops: integer

    }

    countries.id_country -> generic_fact_table.id_country: 1,n
    countries.id_country -> fact_table_flights_countries.id_country: 1,n
    cities.id_city -> generic_fact_table.id_city: 1,n
    timezones.id_timezone -> generic_fact_table.id_timezone: 1,n
    airports.id_airport -> generic_fact_table.id_airport: 1,n
    aircrafts.id_aircraft -> generic_fact_table.id_aircraft: 1,n
    airlines.id_airline -> generic_fact_table.id_airline: 1,n
    flight_schedules.id_flight_schedules -> generic_fact_table.id_flight_schedules: 1,n
    flight_schedules.id_flight_schedules -> fact_table_flights_countries.id_flight_schedules: 1,n

}