vars: {
    d2-config: {
        layout-engine: elk
    }
}

title: |md
  # RAW DATA FROM LH API
| { near: top-center }


DST_RAW_AIRCRAFTS: {
    shape: sql_table
    style: {fill: blue}
    AIRCRAFTCODE: VARCHAR {constraint: [primary_key]}
    AIRLINEEQUIPCODE: VARCHAR
    AICRAFTNAME: VARCHAR
}

DST_RAW_AIRLINES: {
    shape: sql_table
    style: {fill: blue}
    AIRLINEID: VARCHAR 
    AIRLINENAME: VARCHAR
    AIRLINEID_ICAO: VARCHAR
}

DST_RAW_AIRPORTS: {
    shape: sql_table
    style: {fill: blue}
    AIRPORTCODE: VARCHAR 
    CITYCODE: VARCHAR
    COUNTRYCODE: VARCHAR
    LOCATIONTYPE: VARCHAR
    AIRPORTNAME: VARCHAR
    LATITUDE: VARCHAR
    LONGITUDE: VARCHAR
    TIMEZONEID: VARCHAR
    UTCOFFSET: VARCHAR
}

DST_RAW_CITIES: {
    shape: sql_table
    style: {fill: blue}
    CITYCODE: VARCHAR
    AIRPORTCODE: VARCHAR 
    COUNTRYCODE: VARCHAR
    NAME: VARCHAR
    TIMEZONEID: VARCHAR
    UTCOFFSET: VARCHAR
}

DST_RAW_COUNTRIES: {
    shape: sql_table
    style: {fill: blue}
    COUNTRYCODE: VARCHAR 
    COUNTRYNAME: VARCHAR
}	

DST_RAW_FLIGHT_SCHEDULES: {
    shape: sql_table
    style: {fill: blue}
    AIRLINEID: VARCHAR
    FLIGHTNUMBER: NUMBER
    DAYSOFOPERATION: NUMBER
    STARTDATE: VARCHAR
    ENDATE: VARCHAR
    AIRCRAFTTYPE: VARCHAR
    DESTINATION: VARCHAR
    ORIGIN: VARCHAR
    SERVICETYPE: VARCHAR
    AIRCRAFTDEPARTURETIMEUTC: NUMBER
    AIRCRAFTARRIVALTIMEUTC: NUMBER
    CONFIGURATIONVERSION: VARCHAR
    AIRCRAFTOWNER: VARCHAR
}

DST_RAW_FLIGHT_STATUS: {
    shape: sql_table
    style: {fill: blue}
    DEPARTUREAIRPORTCODE: VARCHAR 
    DEPARTUREDATETIMEUTC: DATETIME
    DEPARTURETIMESTATUSCODE: VARCHAR
    DEPARTUEACTUALDATETIMEUTC: DATETIME
    DEPARTURETERMINALNAME: VARCHAR
    DEPARTURETERMINALGATE: VARCHAR
    ARRIVALAIRPORTCODE: VARCHAR 
    ARRIVALDATETIMEUTC: DATETIME
    ARRIVALTIMESTATUSCODE: VARCHAR
    ARRIVALTIMESTATUSDEFINITION: VARCHAR
    ARRIVALACTUALDATETIMEUTC: DATETIME
    ARRIVALTERMINALNAME: VARCHAR
    ARRIVALTERMINALGATE: VARCHAR
    SERVICETYPE: VARCHAR
    OPERATINGCARRIERAIRLINEID: VARCHAR
    OPERATINGCARRIERFLIGHTNUMBER: NUMBER
    MARKETINGCARRIERAIRLINEID: VARCHAR
    MARKETINGCARRIERFLIGHTNUMBER: NUMBER
    AIRCRAFTCODE: VARCHAR
    FLIGHTSTATUSCODE: VARCHAR
    FLIGHTSTATUSDEFINITION: VARCHAR
}		    
