vars: {

    d2-config: {
  
      layout-engine: elk
    }
  
  }

title: |md
  # STAR DATA FROM 3NF
| { near: top-center }


DST_DIM_AIRLINES: {
    shape: sql_table
    style: {fill: green}
    AIRLINEID: VARCHAR {constraint: [primary_key]}
    AIRLINENAME: VARCHAR
    AIRLINEID_ICAO: VARCHAR
}

DST_DIM_AIRCRAFTS: {
    shape: sql_table
    style: {fill: green}
    AIRCRAFTCODE: VARCHAR  {constraint: [primary_key]}
#    AIRLINEEQUIPCODE: VARCHAR
    AICRAFTNAME: VARCHAR
}


DST_DIM_AIRPORTS: {
    shape: sql_table
    style: {fill: green}
    AIRPORTCODE: VARCHAR {constraint: [primary_key]}
    AIRPORTNAME: VARCHAR
    LOCATIONTYPE: VARCHAR
    CITYCODE: VARCHAR
    CITYNAME: VARCHAR
    TIMEZONEID: VARCHAR
    UTCOFFSET: VARCHAR
    COUNTRYCODE: VARCHAR
    COUNTRYNAME: VARCHAR
    LATITUDE: VARCHAR
    LONGITUDE: VARCHAR
}

DST_FACT_FLIGHTS: {
    shape: sql_table
    style: {fill: green}
    FLIGHTID:  {constraint: [primary_key]}
    FLIGHTNUMBER: NUMBER
    SERVICETYPECODE: VARCHAR {constraint: foreign_key}
    AIRCRAFTCODE: VARCHAR {constraint: foreign_key}
    AIRCRAFTOWNER: VARCHAR {constraint: foreign_key}
    DEPARTUREAIRPORTCODE: VARCHAR {constraint: foreign_key}
    DEPARTURETIMESTATUSCODE: VARCHAR {constraint: foreign_key}
    DEPARTUREDATEID: DATE {constraint: foreign_key}
    DEPARTURETIMEGAP: NUMBER
    # DEPARTURETERMINALGATE: VARCHAR {constraint: foreign_key}
    # ARRIVALTERMINALGATE: VARCHAR {constraint: foreign_key}
    ARRIVALAIRPORTCODE: VARCHAR {constraint: foreign_key}
    ARRIVALTIMESTATUSCODE: VARCHAR {constraint: foreign_key}
    ARRIVALDATEID: DATE {constraint: foreign_key}
    ARRIVALTIMEGAP: NUMBER
    TOTALTIMEDIFF: NUMBER
    # CONFIGURATIONVERSION: VARCHAR
    OPERATINGCARRIERAIRLINEID: VARCHAR {constraint: foreign_key}
    # OPERATINGCARRIERFLIGHTNUMBER: NUMBER
    MARKETINGCARRIERAIRLINEID: VARCHAR {constraint: foreign_key}
    # MARKETINGCARRIERFLIGHTNUMBER: NUMBER
    FLIGHTSTATUSCODE: VARCHAR {constraint: foreign_key}
}

DST_DIM_SERVICE_TYPES {
    shape: sql_table
    style: {fill: green}
    SERVICETYPECODE: VARCHAR {constraint: [primary_key]}
    SERVICETYPEDESC: VARCHAR
    SERVICETYPEAPP: VARCHAR
    SERVICETYPECONTENT: VARCHAR
}


DST_DIM_TIME_STATUS {
    shape: sql_table
    style: {fill: green}
    TIMESTATUSCODE: VARCHAR {constraint: [primary_key]}
    TIMESTATUSDEFINITION: VARCHAR
}

DST_DIM_DATE {
    shape: sql_table
    style: {fill: green}
    DATEID: VARCHAR {constraint: [primary_key]}
    DATEFULL: DATE
    DATEYEAR: NUMBER
    DATEMONTH: VARCHAR
    DATEWEEK: NUMBER
    DATEDAY: VARCHAR
}

DST_DIM_FLIGHT_STATUS {
    shape: sql_table
    style: {fill: green}
    FLIGHTSTATUSCODE: VARCHAR {constraint: [primary_key]}
    FLIGHTSTATUSDEFINITION: VARCHAR
}


DST_FACT_FLIGHTS.DEPARTUREDATEID -> DST_DIM_DATE.DATEID: 1,n
DST_FACT_FLIGHTS.ARRIVALDATEID -> DST_DIM_DATE.DATEID: 1,n
DST_FACT_FLIGHTS.DEPARTUREAIRPORTCODE -> DST_DIM_AIRPORTS.AIRPORTCODE: 1,n
DST_FACT_FLIGHTS.ARRIVALAIRPORTCODE -> DST_DIM_AIRPORTS.AIRPORTCODE: 1,n
DST_FACT_FLIGHTS.AIRCRAFTCODE -> DST_DIM_AIRCRAFTS.AIRCRAFTCODE: 1,n
DST_FACT_FLIGHTS.SERVICETYPECODE -> DST_DIM_SERVICE_TYPES.SERVICETYPECODE: 1,n
DST_FACT_FLIGHTS.DEPARTURETIMESTATUSCODE -> DST_DIM_TIME_STATUS.TIMESTATUSCODE: 1,n
DST_FACT_FLIGHTS.ARRIVALTIMESTATUSCODE -> DST_DIM_TIME_STATUS.TIMESTATUSCODE: 1,n
DST_FACT_FLIGHTS.FLIGHTSTATUSCODE -> DST_DIM_FLIGHT_STATUS.FLIGHTSTATUSCODE: 1,n
DST_FACT_FLIGHTS.OPERATINGCARRIERAIRLINEID -> DST_DIM_AIRLINES.AIRLINEID: 1,n
DST_FACT_FLIGHTS.MARKETINGCARRIERAIRLINEID -> DST_DIM_AIRLINES.AIRLINEID: 1,n

